Courses/apps/course/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
path('', views.index, name = 'index'),
path('<int:course_id>/', views.courseview, name = 'courseview'),
]

Courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('courses/', include('course.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Courses/apps/course/models.py
import datetime
from django.db import models
from django.utils import timezone

class Course(models.Model):
    course_title = models.CharField('Name of course', max_length = 200)
    course_description = models.TextField("Descriptiom of cource")
    date_of_start = models.DateTimeField('Date of begining of course')
    # cost_of_course = models.TextField('Cost_of_course')
    # date_of_end = models.DateTimeField('Date of course end')
    # course_image = models.ImageField(null=True, blank=True, upload_to="imges/", verbose_name="Изображение")
    

    def __str__(self):
        return self.course_title
      

    def Meta():
        verbose_name = "Course"
        verbose_name_plural = "Courses"

Courses/apps/course/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Course
from django.urls import reverse

def index(request):
    latest_courses_list = Course.objects.order_by('-date_of_start')[:5]
    return render(request, 'courses/list.html', {'latest_courses_list' : latest_courses_list})

    
def courseview(request, course_id):
    try:  
        a = Course.objects.get( id = course_id)
    except:
        raise Http404("Курс не найден!")
    return render(request, 'courses/courseview.html', {'course' : a})

Courses/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">   
    <title>{% block title %} Courses {% endblock %}</title>
</head>
<style type="text/css">
	body{
		background-color: lightgrey;
	}
</style>
<body>

{% block content %}
	
{% endblock %}

</body>
</html>

Courses/templates/courses/courseview.html
{% extends 'base.html' %}

{% block title %}{{course.course_title}}{% endblock %}


{% block content %}


<!-- Форма подачи заявки на курс не реализована -->
<div class="jumbotron" >
  <h1 class="display-4"><h2>{{course.course_title}}</h2></h1>
  <p class="lead">
	  <div class="alert alert-dark" role="alert"><p>{{course.course_description}}</p></div></p>
	  	<hr class="my-4">
	  <p><div class="alert alert-warning alert-dismissible fade show" role="alert">
		  <strong>Поторопись!</strong>  Курс стартует {{course.date_of_start}}
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  </div></p>

  <button style="margin: 20px;" type="button" class="btn btn-success" data-toggle="tooltip" data-placement="bottom" title="%не реализовано%">
  	<a style="color: white; " href="#">Записаться на курс</a>
  </button>

  <button style="margin: 20px;" type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="bottom" title="К списку курсов">
	  <a style="color: white; " href="/courses">К списку всех курсов</a>
  </button>
</div>



{% endblock %}

Courses/templates/courses/list.html
{% extends 'base.html' %}


{% block title %} List of courses {% endblock %}


{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'list.css' %}" />

{% block content %}

    {% if latest_courses_list %}
        {% for a in latest_courses_list %}
        <div style=" position: relative; top: 20px; ">
		    <div class="card" style="width: 18rem; position: relative; left: 40%;  text-align: center; align-items: center; box-shadow: 0 0 10px rgba(0,0,0,0.5);">
			   {% load static %}
			   <img style="width:280px;" src= '{% static "images/coding.jpeg" %}' alt="Coding photo"><!-- normal image not working -->
			   <div class="card-body">
				    <h5 class="card-title">{{a.course_title}}</h5>
				    <hr>
				    <p class="card-text">{{a.course_description}}</p>
				    <button type="button" class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Открыть описание курса">
				      <a style="color:white;" href="{% url 'courses:courseview' a.id %}">{{a.course_title}}</a>>
					</button>
					<hr>
			   </div>
			</div>
        {% endfor %}
    {% else %}
        No course found
    {% endif %}


 
{% endblock %}